spring.application.name=shipment-engine-svc
server.port=8443

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console

#Configure Hibernate DDL (Data Definition Language) behavior
spring.jpa.hibernate.ddl-auto=update

############## API URL PROPS ##########
api-url.payment-validation.path=https://localhost:8444/payment-validation-svc/validatePayment

############## JOB PROPS #########
scheduled-job.payment-validation.polling-interval=5000
scheduled-job.payment-validation.attempts=5





